// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJF801dd3sywhgzDlCU58RaW8qm3wpM5E',
    appId: '1:1026368824052:web:21c0d2bb6c2042cb4df4a1',
    messagingSenderId: '1026368824052',
    projectId: 'bk-chatapp-5e9d7',
    authDomain: 'bk-chatapp-5e9d7.firebaseapp.com',
    storageBucket: 'bk-chatapp-5e9d7.appspot.com',
    measurementId: 'G-J4TCXTH85Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW9u2dRpug11fk8FC9HIy_E_hztuIxBdo',
    appId: '1:1026368824052:android:31492b0e08a7eb004df4a1',
    messagingSenderId: '1026368824052',
    projectId: 'bk-chatapp-5e9d7',
    storageBucket: 'bk-chatapp-5e9d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvi_CtRYrlk0Rh8PDO03MYUrdZvV9egM',
    appId: '1:1026368824052:ios:cdef759b83d445de4df4a1',
    messagingSenderId: '1026368824052',
    projectId: 'bk-chatapp-5e9d7',
    storageBucket: 'bk-chatapp-5e9d7.appspot.com',
    iosClientId: '1026368824052-0joeg84daptkf067dfj8qimvqqkcahn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bkChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvi_CtRYrlk0Rh8PDO03MYUrdZvV9egM',
    appId: '1:1026368824052:ios:cdef759b83d445de4df4a1',
    messagingSenderId: '1026368824052',
    projectId: 'bk-chatapp-5e9d7',
    storageBucket: 'bk-chatapp-5e9d7.appspot.com',
    iosClientId: '1026368824052-0joeg84daptkf067dfj8qimvqqkcahn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bkChatapp',
  );
}
